server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wood
    username: wood
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
