server:
  port: 8080


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2560KB
      max-request-size: 2560KB

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

