spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wood
    username: wood
    password: 1234

file:
  container-path: /Users/sungyu/Desktop/wood/container
  uploadfile-path: /Users/sungyu/Desktop/wood/upload