server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wood
    username: root
    password: skck0226
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
