spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/wood
    username: wood
    password: 1234

file:
  container-path: /Users/choeseunghwan/Desktop/wood/containers/
  uploadfile-path: /Users/choeseunghwan/Desktop/wood/uploadFiles/