server:
  port: 8080


spring:
  datasource:
    url: jdbc:mariadb://wood_db:3306/wood
    username: wood
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 2560KB
      max-request-size: 2560KB

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

file:
  dockerImage-path: /Users/sungyu/Desktop/wood/
  container-path: /Users/sungyu/Desktop/wood/container/
  uploadfile-path: /Users/sungyu/Desktop/wood/upload/
  testcase-path: /Users/sungyu/Desktop/wood/testcase/